sudo: required 
services: 
  - docker

before_install:
  - docker build -t zgodwin1/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run zgodwin1/react-test npm test -- --coverage

after_success:
  - docker build -t zgodwin1/multi-client ./client
  - docker build -t zgodwin1/multi-nginx ./nginx
  - docker build -t zgodwin1/multi-server ./server
  - docker build -t zgodwin1/multi-worker ./worker
  #Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #Take thoes images and push to docker hub
  - docker push zgodwin1/multi-client
  - docker push zgodwin1/multi-nginx
  - docker push zgodwin1/multi-server
  - docker push zgodwin1/multi
